### ISSUE TITLE
Make the linear stuff happen

### ISSUE THREAD

**Issue by treeowl** [linear-generics/linear-generics#1]
This repository is a forked version of `generic-deriving`. The only change so far is that it derives `Generic1` instances that don't use `fmap` for compositions. Additionally, following and [this comment by Ryan Scott](https://gitlab.haskell.org/ghc/ghc/-/issues/7492#note_380348), they don't use the `Rec1` type. These are much more efficient, and they also happen to avoid fundamental linearity problems. To actually make this package fit for purpose, some more work is necessary:

- [x] Add custom `Generic` and `Generic1` classes with linearly-typed `to`, `from`, `to1`, and `from1`.
- [x] Add a custom `:.:`. This will allow users to share generic-deriving classes between `GHC.Generics` and the linear version, by just adding an extra instance. This doesn't help with linearity stuff, but this package is also about a more efficient `Generic1`!
- [x] `Generic` admits a simple default implementation using `GHC.Generics`. This is slightly unsafe because users can write custom implementations of `GHC.Generics.Generic` if they like, and these may potentially be non-linear. `Generic1` similarly admits a default implementation in the case that `GHC.Generics.Rep1` doesn't contain any compositions. Offer `DerivingVia` targets to do this magic. This method can derive some instances that the current Template Haskell stuff can't.
- [x] Make the Template Haskell produce linear method definitions. For GHC 9.2, I *expect* this to be easy. For GHC 9.0, ~~I expect we'll need some workarounds. In the worst case scenario, we might use `toLinear` to fake everything in 9.0.~~ we need to work around a bug in linearity of empty case. I hope that's all we'll need.
- [x] Rewrite/modify all the many, many instance declarations/derivations in the package to accommodate the new classes and `:.:`. This ~~looks like~~ was a pain; ~~I don't have a great plan yet~~ it's mostly done now. I imagine we're missing types here and there, but we can deal with that as it comes up.
- [x] Clear out much of the inherited `generic-deriving` API. For the moment, that probably means leaving the code but not exporting it. In particular:
      1. We probably don't want to offer deriving options yet because we don't know what options we might need.
      2. We probably don't want to offer `make` functions yet because we don't know when/whether they'll be useful.
 Once we have more of a clue, we may reintroduce some of that, and otherwise delete it.
- [x] Rename the top level of the module hierarchy. This isn't `generic-deriving`!

One unfortunate matter is that neither `GHC.Generics` nor Template Haskell currently supports types with nonlinear constructors. I don't know how far that lack of support goes. One hypothetical partial workaround might be for the user to supply a hand-constructed `Rep`/`Rep1` and use Template Haskell to produce `to`, `from`, `to1`, and `from1` based on that type. Even if that works, it will be quite unpleasant.

**Comment by treeowl** [comment]
@RyanGlScott and @dreixel, I'm hoping one or both of you can give me a bit more insight into things like optional kind signatures and the need for/desirability of `make` functions.

**Comment by RyanGlScott** [comment]
I'm going to optimistically claim that none of the adjustable settings in `generic-deriving`'s `Options` type are actually needed in `linear-generics`:

* `repOptions`' default setting is to generate an associated `Rep(1)` instance directly (without going through an auxiliary type synonym). This is definitely the most sensible option. The only reason I had to make this configurable is because of old Template Haskell bugs on GHC 7.0 through 7.4 that prevented the direct approach from working. Since `linear-generics` only supports GHC 9.0 and later, this isn't an issue here.
* `emptyCaseOptions` only exists for the benefit of GHC 7.6 and earlier, which did not support `EmptyCase`. Again, this isn't an issue for `linear-generics`.
* My memory on `kindSigOptions` is a bit fuzzy. The default setting (`kindSigOptions = True`) results in generated `Generic(1)` instances having explicit kind annotations. This is a sensible default option, and there are some examples that won't typecheck without this. I recall there being some corner cases where this caused problems on earlier GHCs, although I can't recall exactly what they were now. I think it would be safe to always generate explicit kind annotations in `linear-generics`.

As far as `make-` functions go, they primarily exist in service of defining `Generic1` instances that involve `(:.:)`. The problem is that in order to generate such a `Generic1` in a completely automated fashion, you have to infer where the `Functor` constraints should go. For example:

```hs
newtype Compose f g a = Compose (f (g a))
$(deriveAll1 ''Compose)
```

Here, the generated `Generic1` instance should be:

```hs
instance Functor f => Generic1 (Compose f g) where
```

Note that there is a `Functor f` constraint but not a `Functor g` constraint. Figuring this out turns out to be really annoying in practice, as doing it correctly in all cases would be tantamount to performing type inference on Template Haskell ASTs. I've tried to do so before, but I was ultimately never satisfied with the heuristics that I came up with.

In the end, I decided that if you wanted to generate a `Generic1` instance that requires an instance context, the burden is on you to write the context yourself. This is where the `make-` functions come in. They let you write things like:

```hs
instance Functor f => Generic1 (Compose f g) where
  type Rep1 (Compose f g) = $(makeRep1 ''Compose) f g
  from1 = $(makeFrom1 ''Compose)
  to1   = $(makeTo1 ''Compose)
```

This gives allows you avoid most of the boilerplate while still having precise control over the instance context.

Having said all that, it's unlikely that you'll have to worry about this sort of situation in `linear-generics`. This is because you're using a different convention for `(:.:)` which avoids the need for `Functor` constraints entirely. As a result, I believe you won't ever need to generate instance contexts at all. If you wanted to, you could just remove the `make-` functions entirely, and they probably wouldn't be missed.

**Comment by RyanGlScott** [comment]
> Purely for the sake of curiosity: what makes it hard to figure out where the `Functor` constraints go?

For starters, you can't figure out what parts of the `Generic1` instance need `Functor` constraints without traversing all the data constructors and analyzing which types are used at the first arguments to `(:.:)` in a `Rep1` instance. That's annoying, but technically doable. Things get more complicated from there, unfortunately. Let's pick a slightly more complex example:

```hs
newtype T f g a = MkT (IdentityT f (g a))
```

If you naïvely walk over the fields of the `MkT` data type, you'd end up with an instance context of `Functor (IdentityT f)`. But that's not quite satisfactory either, as you can simplify this to just `Functor f`. In some other cases, you could simplify all of the `Functor` constraints away, such as in this example:

```hs
newtype S g a = MkS (Maybe (g a))
```

Correctly simplifying these constraints requires looking up the `Functor` instances for the appropriate types and doing a sort of fixpoint calculation based on this information. GHC is able to do this quite precisely since its `deriving` machinery works over Core, where all of the type information is explicit. In Template Haskell, however, this is not always the case, which makes doing this sort of type inference-esque algorithm a real pain.

**Comment by treeowl** [comment]
Thanks!

**Comment by treeowl** [comment]
@RyanGlScott, funny thing: I actually do need to watch out for empty case, though users shouldn't play any role in that. GHC 9.0 doesn't recognize empty case match as consuming a value, so in that context I need to insert some `toLinear` applications. Bleh.

**Comment by treeowl** [comment]
@RyanGlScott, do you think I need any exports other than `deriveAll0`, `deriveAll1`, and `deriveAll0And1`?

**Comment by aspiwack** [comment]
> @RyanGlScott, funny thing: I actually do need to watch out for empty case, though users shouldn't play any role in that. GHC 9.0 doesn't recognize empty case match as consuming a value, so in that context I need to insert some `toLinear` applications. Bleh.

This is weird, I thought we had addressed empty cases for 9.0. @monoidal can you remind me what the status of empty case is?

**Comment by RyanGlScott** [comment]
> there's a comment to the effect that `generic-deriving` doesn't want to use TH internally so that it can be used for a stage 1 compiler. Is that of any relevance to `linear-generics`?

I decided to be extra cautious in avoiding the use of the `TemplateHaskell` extension within the library itself since `generic-deriving` is so widely depended on. `linear-generics` doesn't have that constraint, so you may feel differently. 

> If I _do_ use TH internally, the comment suggests that names in `TH.Internal` can be obtained more nicely. Could you show me how? I still don't know Template Haskell at all.

Yes, the names in `TH.Internal` are defined in an extremely roundabout way since pre-8.0 GHCs lacked the `TemplateHaskellQuotes` extension. If you have access to `TemplateHaskellQuotes`, then you can define Template Haskell quotes without using Template Haskell splices. The latter is only available with the `TemplateHaskell` extension, and that is what gives stage-0 compilers trouble.

This is all to say: since you're using modern GHCs: don't do what `TH.Internal` does. Just quote the names directly (e.g., `''Generic`).

> do you think I need any TH exports other than `deriveAll0`, `deriveAll1`, and `deriveAll0And1`?

I think those would suffice.

On a related note, I've always hated the name "`deriveAll-`". That is what it was originally called in `generic-deriving` before I became maintainer, but if I had created it from scratch, I'd probably have called it `deriveGeneric-` instead.

**Comment by treeowl** [comment]
@RyanGlScott, I just ran into a troubling piece of documentation regarding kind signatures:

```haskell
'KindSigOptions': By default, all derived instances will use explicit kind
signatures (when the 'KindSigOptions' is 'True'). You might wish to set the
'KindSigOptions' to 'False' if you want a 'Generic'/'Generic1' instance at
a particular kind that GHC will infer correctly, but the functions in this
module won't guess correctly. For example, the following example will only
compile with 'KindSigOptions' set to 'False':

@
newtype Compose (f :: k2 -> *) (g :: k1 -> k2) (a :: k1) = Compose (f (g a))
$('deriveAll1Options' False ''Compose)
@
```

Does this mean I need to keep that one option around? Or have you actually fixed that issue?

**Comment by RyanGlScott** [comment]
That documentation is somewhat out of date. I think that was harkening back to an era when `Generic1` had the kind `(Type -> Type) -> Constraint` rather than `(k -> Type) -> Constraint`, and `generic-deriving` had to do some clever kind substitution to work around this when `kindSigOptions = True`. That shouldn't be relevant anymore with `Generic1`'s current kind, so I'm going to boldly claim that this isn't relevant to your needs. I'll try to update this documentation at some point in the near future.

There's a separate bug involving `kindSigOptions = False` that I've reported at dreixel/generic-deriving#80, but since you're always assuming that `kindSigOptions = True`, that shouldn't apply here.

**Comment by RyanGlScott** [comment]
That is an expected error in some sense. While GHC complains about the kind, the real problem is the lack of a `Functor` constraint, which `generic-deriving` makes no attempt to infer. See the Haddocks [here](https://hackage.haskell.org/package/generic-deriving-1.14.1/docs/Generics-Deriving-TH.html#g:2).

**Comment by treeowl** [comment]
Oh, bah, that junk. *sigh*. All right. I'll finish weeding and see if it works with my encoding.

**Comment by treeowl** [comment]
@RyanGlScott  I did all the weeding, and worked around the `case` multiplicity issue, but there is a kind signature problem in `TypeInTypeSpec`. I find it *quite* mysterious. Here are the instance head and `Rep1` from the splice:

```haskell
    instance Generic1 (TyCon (x_a7ow :: ghc-prim-0.7.0:GHC.Types.Type) (a_a7ox :: x_a7ow) :: k_a7ov
                                                                                             -> ghc-prim-0.7.0:GHC.Types.Type) where
      type Rep1 (TyCon (x_a7ow :: ghc-prim-0.7.0:GHC.Types.Type) (a_a7ox :: x_a7ow) :: k_a7ov
                                                                                       -> ghc-prim-0.7.0:GHC.Types.Type) = GHC.Generics.D1 ('GHC.Generics.MetaData "TyCon" "TypeInTypeSpec" "main" 'False) (GHC.Generics.C1 ('GHC.Generics.MetaCons "TyCon" 'GHC.Generics.PrefixI 'False) ((GHC.Generics.:*:) ((GHC.Generics.:*:) (GHC.Generics.S1 ('GHC.Generics.MetaSel 'Nothing 'GHC.Generics.NoSourceUnpackedness 'GHC.Generics.NoSourceStrictness 'GHC.Generics.DecidedLazy) (GHC.Generics.Rec0 k_a7ov)) (GHC.Generics.S1 ('GHC.Generics.MetaSel 'Nothing 'GHC.Generics.NoSourceUnpackedness 'GHC.Generics.NoSourceStrictness 'GHC.Generics.DecidedLazy) (GHC.Generics.Rec0 x_a7ow))) ((GHC.Generics.:*:) (GHC.Generics.S1 ('GHC.Generics.MetaSel 'Nothing 'GHC.Generics.NoSourceUnpackedness 'GHC.Generics.NoSourceStrictness 'GHC.Generics.DecidedLazy) (GHC.Generics.Rec0 (Proxy a_a7ox))) (GHC.Generics.S1 ('GHC.Generics.MetaSel 'Nothing 'GHC.Generics.NoSourceUnpackedness 'GHC.Generics.NoSourceStrictness 'GHC.Generics.DecidedLazy) ((linear-generics-1.14.1:Generics.Deriving.Base.Internal.:.:) GHC.Generics.Par1 (TyCon x_a7ow a_a7ox))))))
```

And here's the error message:

```
tests/TypeInTypeSpec.hs:38:19: error:
    • Couldn't match type ‘k’ with ‘Bool’
      Expected: Rep1 @{k} @Bool (TyCon @k Bool 'False) 'True
        Actual: Rep1 @{Bool} @Bool (TyCon @Bool Bool 'False) 'True
      ‘k’ is a rigid type variable bound by
        the type signature for:
          rep :: forall {k}. Rep1 (TyCon Bool 'False) 'True
        at tests/TypeInTypeSpec.hs:37:13-49
    • In the expression:
        gen1PolyKinds $ let x = TyCon True False Proxy x in x
      In an equation for ‘rep’:
          rep = gen1PolyKinds $ let x = TyCon True False Proxy x in x
      In the second argument of ‘($)’, namely
        ‘let
           rep :: Rep1 (TyCon Bool 'False) 'True
           rep = gen1PolyKinds $ let ... in x
         in seq rep () `shouldBe` ()’
    • Relevant bindings include
        rep :: Rep1 (TyCon Bool 'False) 'True
          (bound at tests/TypeInTypeSpec.hs:38:13)
   |
38 |             rep = gen1PolyKinds $ let x = TyCon True False Proxy x in x
```

I really don't see where the problem is, but *something* must be wrong.

**Comment by RyanGlScott** [comment]
Currently, you are defining `Generic1` like this:

```hs
type Generic1 :: forall k. (k -> Type) -> Constraint
class Generic1 f where
  type family Rep1 f :: k -> Type
```

This most likely isn't doing what you intended it to. [Kind-level `forall`s don't interact with `ScopedTypeVariables`](https://ryanglscott.github.io/2021/04/05/why-kind-level-foralls-dont-interact-with-scopedtypevariables/), so the `k` in `type family Rep1 f :: k -> Type` isn't the same `k` as in the standalone kind signature. It's as if you had written this:

```hs
type Generic1 :: forall k. (k -> Type) -> Constraint
class Generic1 f where
  type family Rep1 f :: distinctK -> Type
```

This means that `Rep1 :: (k -> Type) -> distinctK -> Type`. `TypeInTypeSpec` relies on these kind variables being the same in order to kind-check, so when `Rep1` has this more general kind, things go awry.

A fix is to annotate the kind of `f` in the `class` declaration:

```hs
type Generic1 :: forall k. (k -> Type) -> Constraint
class Generic1 (f :: k -> Type) where
  type family Rep1 f :: k -> Type
```

(This is a bit unfortunate. [This proposal](https://github.com/ghc-proposals/ghc-proposals/pull/425) offers a way to make things less unfortunate.)

**Comment by treeowl** [comment]
Oh wow, that really is surprising. Thanks! And it fixes the problem!
