### ISSUE TITLE
Add comment on kind signatures

### ISSUE THREAD

**Issue by treeowl** [linear-generics/linear-generics#8]
@aspiwack points to a comment in `Generics.Linear.TH`:

```haskell
{-
If we dropped the kind signature for a in a derived instance for Fam a, then GHC
would have no way of knowing which instance we are talking about.
-}
```

He says,

> It would be worth writing a derived instance without and with a kind signature to be able to point concretely at what goes wrong.

**Comment by RyanGlScott** [comment]
It does matter, but for reasons unrelated to the `T` example above. The reason the `TypeInTypeSpec` module would fail to compile without kind signatures is because of the rationale behind this example:

https://github.com/linear-generics/linear-generics/blob/92db9c9cbf48fa83f823695e75c9fa8a384c8b38/src/Generics/Linear/TH.hs#L574-L587

`TypeInTypeSpec` has a data type very similar to `S` where a kind variable is used as a field type.

**Comment by RyanGlScott** [comment]
I'm preparing a PR now.
